### ISSUE TITLE
getDetailsRow --> NPE

### ISSUE THREAD

**Issue by Dream-of-Electric-Sheep** [uservoice/uservoice-android-sdk#112]
```
0   
java.lang.NullPointerException
1   
at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.getDetailRows(PostIdeaAdapter.java:49)
2   
at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.getRows(InstantAnswersAdapter.java:93)
3   
at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.getRows(PostIdeaAdapter.java:59)
4   
at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.getCount(InstantAnswersAdapter.java:105)
5   
at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:804)
6   
at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:7563)
7   
at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
8   
at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
9   
at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter$3.onModel(InstantAnswersAdapter.java:1)
10  
at com.uservoice.uservoicesdk.model.Article$3.onComplete(Article.java:54)
11  
at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:1)
12  
at android.os.AsyncTask.finish(AsyncTask.java:631)
13  
at android.os.AsyncTask.access$600(AsyncTask.java:177)
14  
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
15  
at android.os.Handler.dispatchMessage(Handler.java:99)
16  
at android.os.Looper.loop(Looper.java:176)
17  
at android.app.ActivityThread.main(ActivityThread.java:5319)
18  
at java.lang.reflect.Method.invokeNative(Native Method)
19  
at java.lang.reflect.Method.invoke(Method.java:511)
20  
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
21  
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22  
at dalvik.system.NativeStart.main(Native Method)
```

Sorry, have no further details (apart from version number: 1.1.0).

**Comment by gramarao** [comment]
I guess #200 will also be a dup of #112 - is this a known issue and do we have plan on when fix for this will be available?

**Comment by thuytrinh** [comment]
Same crash that happened to us:
```
Fatal Exception: java.lang.NullPointerException
       at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.getDetailRows(PostIdeaAdapter.java:52)
       at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.getRows(InstantAnswersAdapter.java:94)
       at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.getRows(PostIdeaAdapter.java:62)
       at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.getCount(InstantAnswersAdapter.java:106)
       at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:805)
       at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6623)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
       at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter$3.onModel(InstantAnswersAdapter.java:293)
       at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter$3.onModel(InstantAnswersAdapter.java:283)
       at com.uservoice.uservoicesdk.model.Article$3.onComplete(Article.java:65)
       at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:121)
       at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:38)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

UV SDK 1.2.4.
