### ISSUE TITLE
TopicActivity NPE after pause

### ISSUE THREAD

**Issue by Dream-of-Electric-Sheep** [uservoice/uservoice-android-sdk#114]
From Play Dev Console

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dream_of_electric_sheep.android.m_parking/com.uservoice.uservoicesdk.activity.TopicActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2081)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106)
at android.app.ActivityThread.access$700(ActivityThread.java:134)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1217)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4856)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:330)
at android.widget.AbsSpinner.setAdapter(AbsSpinner.java:114)
at android.widget.Spinner.setAdapter(Spinner.java:374)
at com.android.internal.widget.ActionBarView.setDropdownAdapter(ActionBarView.java:766)
at com.android.internal.app.ActionBarImpl.setListNavigationCallbacks(ActionBarImpl.java:1120)
at com.uservoice.uservoicesdk.activity.TopicActivity.onCreate(TopicActivity.java:37)
at android.app.Activity.performCreate(Activity.java:5047)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045)
... 11 more
```

Happened on: Galaxy S3 Mini (golden)
UV version number: 1.1.0

**Comment by austintaylor** [comment]
Known bug that the TopicActivity can't be launched directly. This happens when the host app is pushed out of memory and then the user returns to it.
