### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by alexblack** [uservoice/uservoice-android-sdk#148]
Two of my users have had NPE's here, both were running Android 2.3.4

```
java.lang.NullPointerException
	at com.uservoice.uservoicesdk.activity.SearchActivity.void setupScopedSearch(android.view.Menu)(ProGuard:66)
	at com.uservoice.uservoicesdk.activity.TopicActivity.boolean onCreateOptionsMenu(android.view.Menu)(ProGuard:119)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2266)
	at android.support.v4.app.FragmentActivity$NonConfigurationInstances.onCreatePanelMenu(ProGuard:275)
	at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ProGuard:276)
	at android.support.v7.app.ActionBarActivityDelegate$1.boolean onCreatePanelMenu(int,android.view.Menu)(ProGuard:79)
	at android.support.v7.app.ActionBarActivityDelegateBase.preparePanel(ProGuard:1056)
	at android.support.v7.app.ActionBarActivityDelegateBase.doInvalidatePanelMenu(ProGuard:1259)
	at android.support.v7.app.ActionBarActivityDelegateBase.access$100(ProGuard:80)
	at android.support.v7.app.ActionBarActivityDelegateBase$1.void run()(ProGuard:119)
	at android.os.Handler.handleCallback(Handler.java:593)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3756)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by austintaylor** [comment]
In 1.2.1
