### ISSUE TITLE
Crash on ArticleActivity.onPageFinished (NPE)

### ISSUE THREAD

**Issue by ultrah** [uservoice/uservoice-android-sdk#160]
When I click on any article in the knowledge base, the App crash with a NPE: 

```
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at com.uservoice.uservoicesdk.activity.ArticleActivity$1.onPageFinished(ArticleActivity.java:37)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:495)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver.didFinishLoad(AwContentsClient.java:69)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at android.os.Looper.loop(Looper.java:135)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at android.app.ActivityThread.main(ActivityThread.java:5221)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at java.lang.reflect.Method.invoke(Native Method)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at java.lang.reflect.Method.invoke(Method.java:372)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-11 14:51:20.729  12133-12133/com.example.foo W/System.err? at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

I am using this code to start the activity (as provided):

```
/ Set this up once when your application launches Config config = new Config("myapp.uservoice.com");
config.setForumId(12345);
config.setShowContactUs(false);
UserVoice.init(config, HelpActivity.this);

// Call this wherever you want to launch UserVoice
UserVoice.launchUserVoice(HelpActivity.this);
```

The apps theme is derived from AppCompat.  :

```
compileSdkVersion 21
buildToolsVersion "21.1.2"

compile 'com.uservoice:uservoice-android-sdk:1.2.1'
compile 'com.android.support:support-v4:21.0.3'
compile 'com.android.support:appcompat-v7:21.0.3'
```
Reproduced on different API levels.

**Comment by austintaylor** [comment]
This was a regression that accidentally made it into 1.2.1. Fixed in 1.2.2 (just released).
