### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by alexblack** [uservoice/uservoice-android-sdk#169]
I get a couple of these a week...

java.lang.NullPointerException
	at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.java.util.List getDetailRows()(ProGuard:51)
	at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.java.util.List getRows()(ProGuard:93)
	at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.java.util.List getRows()(ProGuard:61)
	at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.int getCount()(ProGuard:105)
	at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:802)
	at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6287)
	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
	at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.void onButtonTapped()(ProGuard:297)
	at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter$1.void onClick(android.view.View)(ProGuard:162)
	at android.view.View.performClick(View.java:4569)
	at android.view.View$PerformClick.run(View.java:18553)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:212)
	at android.app.ActivityThread.main(ActivityThread.java:5137)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by austintaylor** [comment]
Dup of #112
