### ISSUE TITLE
Another NullPointerException that happened to one of my users

### ISSUE THREAD

**Issue by alexblack** [uservoice/uservoice-android-sdk#171]
java.lang.NullPointerException
	at com.uservoice.uservoicesdk.rest.RestResult.java.lang.String getType()(ProGuard:49)
	at com.uservoice.uservoicesdk.flow.InitManager$2$1.void onError(com.uservoice.uservoicesdk.rest.RestResult)(ProGuard:67)
	at com.uservoice.uservoicesdk.rest.RestTaskCallback.void onComplete(org.json.JSONObject)(ProGuard:17)
                                                     void onError(com.uservoice.uservoicesdk.rest.RestResult)
	at com.uservoice.uservoicesdk.rest.RestTask.void onPostExecute(com.uservoice.uservoicesdk.rest.RestResult)(ProGuard:118)
	at com.uservoice.uservoicesdk.rest.RestTask.void onPostExecute(java.lang.Object)(ProGuard:38)
	at android.os.AsyncTask.finish(AsyncTask.java:417)
	at android.os.AsyncTask.access$300(AsyncTask.java:127)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3770)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by yurii-diachenko** [comment]
Any update on this bug?

**Comment by ewdouglas** [comment]
This crash occurred for a few of our users in SDK v1.2.5, especially after seeing the message "There was an error connecting to UserVoice".

**Comment by mchamler** [comment]
This bug was introduced in this commit: https://github.com/uservoice/uservoice-android-sdk/commit/735d5a0680a0c165f39936b323bd397534cc29aa

Looks like it should be pretty easy to fix.
