### ISSUE TITLE
Null pointer exception on feedback screen next button click.

### ISSUE THREAD

**Issue by jibinms** [uservoice/uservoice-android-sdk#183]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.uservoice.uservoicesdk.model.Forum.getCategories()' on a null object reference
            at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.getDetailRows(PostIdeaAdapter.java:52)
            at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.getRows(InstantAnswersAdapter.java:94)
            at com.uservoice.uservoicesdk.ui.PostIdeaAdapter.getRows(PostIdeaAdapter.java:62)
            at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter.getCount(InstantAnswersAdapter.java:106)
            at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:806)
            at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6129)
            at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
            at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
            at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter$3.onModel(InstantAnswersAdapter.java:293)
            at com.uservoice.uservoicesdk.ui.InstantAnswersAdapter$3.onModel(InstantAnswersAdapter.java:283)
            at com.uservoice.uservoicesdk.model.Article$3.onComplete(Article.java:65)
            at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:121)
            at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:38)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by austintaylor** [comment]
Same as #112
