### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method setOnQueryTextListener on a null object reference

### ISSUE THREAD

**Issue by dkozel** [uservoice/uservoice-android-sdk#184]
This crash occurred repeatedly for one of our users. I do not know the steps to reproduce, but the full crash log is below. The app is currently using Uservoice's 1.2.2 SDK. I've just updated the development version to 1.2.4. Does anyone know if this was fixed in those updates?

Thanks!

Android: 5.0
Manufacturer: samsung
Model: SM-G900F

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setOnQueryTextListener(android.support.v7.widget.SearchView$OnQueryTextListener)' on a null object reference
	at com.uservoice.uservoicesdk.activity.SearchActivity.setupScopedSearch(SearchActivity.java:60)
	at com.uservoice.uservoicesdk.activity.PortalActivity.onCreateOptionsMenu(PortalActivity.java:29)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2921)
	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
	at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
	at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
	at android.support.v7.app.ActionBarActivityDelegateBase.preparePanel(ActionBarActivityDelegateBase.java:979)
	at android.support.v7.app.ActionBarActivityDelegateBase.doInvalidatePanelMenu(ActionBarActivityDelegateBase.java:1182)
	at android.support.v7.app.ActionBarActivityDelegateBase.access$100(ActionBarActivityDelegateBase.java:79)
	at android.support.v7.app.ActionBarActivityDelegateBase$1.run(ActionBarActivityDelegateBase.java:118)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5834)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

**Comment by cyberrob** [comment]
I found in debug mode there won't be crash, but after packaging in release mode the crash will happen for sure.

I found this help!
````
## UserVoice
-keep class android.support.v7.widget.SearchView { *; }
````
found it on [this comment](https://github.com/uservoice/uservoice-android-sdk/issues/147#issuecomment-67482400)
