### ISSUE TITLE
Null Object Reference PortalAdapter.getCount

### ISSUE THREAD

**Issue by bschnack** [uservoice/uservoice-android-sdk#190]
java.lang.NullPointerException: Attempt to read from field 'boolean com.uservoice.uservoicesdk.model.k.c' on a null object reference 
at com.uservoice.uservoicesdk.ui.PortalAdapter.getCount(SourceFile:139) 
at android.widget.AdapterView.isScrollableForAccessibility(AdapterView.java:968) 
at android.widget.AdapterView.onInitializeAccessibilityEvent(AdapterView.java:954) 
at android.widget.AbsListView.onInitializeAccessibilityEvent(AbsListView.java:1530) 
at android.widget.ListView.onInitializeAccessibilityEvent(ListView.java:3876) 
at android.widget.AdapterView.onRequestSendAccessibilityEvent(AdapterView.java:930) 
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:734) 
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:738) 
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:738) 
at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5303) 
at android.view.View.sendAccessibilityEventUnchecked(View.java:5283) 
at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:20995) 
at android.os.Handler.handleCallback(Handler.java:739) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:135) 
at android.app.ActivityThread.main(ActivityThread.java:5299) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by austintaylor** [comment]
Confused by this. We are already checking configLoaded, although I suppose we could actually check whether it is null. Can you give me any more info about when this happens?

https://github.com/uservoice/uservoice-android-sdk/blob/master/UserVoiceSDK/src/com/uservoice/uservoicesdk/ui/PortalAdapter.java#L139

**Comment by bschnack** [comment]
Hello Austin,

We do not have a repro for this, we just know that our users are hitting this more than any other crash by us.  It sounds like the Config is null from the crash logs, so maybe you have some logic where the config is getting removed but it still thinks it is loaded?

Cheers,
Brian

**Comment by mrmaffen** [comment]
Just had the same NPE crash in PortalAdapter.getCount. Here's my log output:
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.uservoice.uservoicesdk.model.ClientConfig.isWhiteLabel()' on a null object reference
            at com.uservoice.uservoicesdk.ui.PortalAdapter.getCount(PortalAdapter.java:139)
            at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:821)
            at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6179)
            at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
            at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
            at com.uservoice.uservoicesdk.ui.PortalAdapter$2.onModel(PortalAdapter.java:77)
            at com.uservoice.uservoicesdk.ui.PortalAdapter$2.onModel(PortalAdapter.java:73)
            at com.uservoice.uservoicesdk.model.Forum$1.onComplete(Forum.java:22)
            at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:121)
            at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:38)
            at android.os.AsyncTask.finish(AsyncTask.java:651)
            at android.os.AsyncTask.-wrap1(AsyncTask.java)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mrmaffen** [comment]
I am able to reproduce this crash by calling "UserVoice.launchUserVoice(getActivity());" and then pressing back immediately. Then calling it again, pressing back and so on. When I repeat this ~10 times, the NPE in PortalAdapter.getCount occurs.

**Comment by mrmaffen** [comment]
Nevermind. I was using the outdated version 1.2.2. I can no longer reproduce this issue with 1.2.4.

**Comment by caltseng** [comment]
I am still able to reproduce this issue with 1.2.4.

**Comment by apkelly** [comment]
I'm seeing this error too using v1.2.2, I'll try updating to v1.2.4 to see if that helps.

Fatal Exception: java.lang.NullPointerException
       at com.uservoice.uservoicesdk.ui.PortalAdapter.getCount(PortalAdapter.java:139)
       at android.widget.ListView.onMeasure(ListView.java:1155)
       at android.view.View.measure(View.java:17495)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:17495)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:17495)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
       at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:453)
       at android.view.View.measure(View.java:17495)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:17495)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:17495)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
       at android.view.View.measure(View.java:17495)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2285)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1396)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1595)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6637)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
       at android.view.Choreographer.doCallbacks(Choreographer.java:614)
       at android.view.Choreographer.doFrame(Choreographer.java:584)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by caltseng** [comment]
As an FYI, I fixed this bug in our code by simply extending the adapter and adding a try-catch around it so it never crashes our code.
