### ISSUE TITLE
Null Pointer Exception EditText.setText

### ISSUE THREAD

**Issue by bschnack** [uservoice/uservoice-android-sdk#191]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference 
at com.uservoice.uservoicesdk.dialog.CommentDialogFragment.onCreateDialog$5709b310(SourceFile:56) 
at android.support.v4.app.DialogFragment.getLayoutInflater(SourceFile:307) 
at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:953) 
at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1136) 
at android.support.v4.app.BackStackRecord.run(SourceFile:739) 
at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:1499) 
at android.support.v4.app.FragmentManagerImpl$1.run(SourceFile:456) 
at android.os.Handler.handleCallback(Handler.java:739) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:135) 
at android.app.ActivityThread.main(ActivityThread.java:5221) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by austintaylor** [comment]
Can you give me any more information about this? I don't see how the EditText could be null.

https://github.com/uservoice/uservoice-android-sdk/blob/master/UserVoiceSDK/src/com/uservoice/uservoicesdk/dialog/CommentDialogFragment.java#L56

**Comment by bschnack** [comment]
Hello Austin,

I am not really sure what you want me to tell you.  Maybe the layout that is being inflated is not correct or something like that.  We do not have a repro.

Cheers, Brian

**Comment by caltseng** [comment]
Austin, 

You can resolve this bug. Turned out to be a bug in our code. 

Thanks, 
CalebT
