### ISSUE TITLE
NPE in Session.java

### ISSUE THREAD

**Issue by shafty023** [uservoice/uservoice-android-sdk#195]
Unsure how this is happening (i.e. repro steps) but I'm getting this crash in Crashlytics.

<img width="942" alt="uservoice_crash" src="https://cloud.githubusercontent.com/assets/397037/8908347/34681254-3441-11e5-8c1b-6b816213a886.png">

**Comment by austintaylor** [comment]
Did you recently update the version of the UserVoice SDK in your app? I can imagine a scenario where this would happen, but it seems pretty obscure.

At any rate we should do something to handle the case where `site` is null. Probably we should wrap the exception and then catch it higher up and close the SDK, since there is no config either in memory or in shared prefs.

**Comment by shafty023** [comment]
Yes I have recently updated the UV sdk. Is there a known issue?

**Comment by martyglaubitz** [comment]
we get something similar only with different linenumbers _java.lang.RuntimeException: Unable to start activity ComponentInfo{my.app/com.uservoice.uservoicesdk.activity.PortalActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
	at android.app.ActivityThread.access$600(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4847)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:535)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.uservoice.uservoicesdk.Session.getSharedPreferences(Session.java:130)
	at com.uservoice.uservoicesdk.Session.getConfig(Session.java:53)
	at com.uservoice.uservoicesdk.model.ClientConfig.loadClientConfig(ClientConfig.java:33)
	at com.uservoice.uservoicesdk.flow.InitManager.init(InitManager.java:31)
	at com.uservoice.uservoicesdk.ui.PortalAdapter.<init>(PortalAdapter.java:61)
	at com.uservoice.uservoicesdk.activity.PortalActivity.onCreate(PortalActivity.java:21)
	at android.app.Activity.performCreate(Activity.java:5187)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
	... 11 more_

**Comment by mchamler** [comment]
Seeing lots of errors like this after updating UserVoice version in our app.

Caused by: java.lang.NullPointerException: 
  at com.uservoice.uservoicesdk.Session.getSharedPreferences (Session.java:130)
  at com.uservoice.uservoicesdk.Session.getConfig (Session.java:53)
  at com.uservoice.uservoicesdk.ui.ContactAdapter.<init> (ContactAdapter.java:36)
  at com.uservoice.uservoicesdk.activity.ContactActivity.createAdapter (ContactActivity.java:19)
  at com.uservoice.uservoicesdk.activity.InstantAnswersActivity.onCreate (InstantAnswersActivity.java:28)
  at com.uservoice.uservoicesdk.activity.ContactActivity.onCreate (ContactActivity.java:13)
  at android.app.Activity.performCreate (Activity.java:6910)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1123)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2746)

Is there a workaround?
