### ISSUE TITLE
Null pointer exception when trying to back press in uservoice

### ISSUE THREAD

**Issue by Eagles2F** [uservoice/uservoice-android-sdk#196]
Config: 
      // Set this up once when your application launches
        final Config config = new Config("xx.uservoice.com");
        config.setForumId(xxxx);
        config.setShowContactUs(false);
        config.setShowKnowledgeBase(false);
        // config.identifyUser("USER_ID", "User Name", "email@example.com");
        UserVoice.init(config, this);
        UserVoice.launchUserVoice(this)

 java.lang.NullPointerException
            at com.uservoice.uservoicesdk.ui.PortalAdapter.getCount(PortalAdapter.java:139)
            at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:804)
            at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6000)
            at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
            at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
            at com.uservoice.uservoicesdk.ui.PortalAdapter$3.onModel(PortalAdapter.java:88)
            at com.uservoice.uservoicesdk.ui.PortalAdapter$3.onModel(PortalAdapter.java:83)
            at com.uservoice.uservoicesdk.model.Article$1.onComplete(Article.java:35)
            at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:121)
            at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:38)
            at android.os.AsyncTask.finish(AsyncTask.java:631)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5457)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by austintaylor** [comment]
Is this the same as #197 or a different issue? Which view are you trying to back out of?
