### ISSUE TITLE
NPE @ parseColor

### ISSUE THREAD

**Issue by gramarao** [uservoice/uservoice-android-sdk#200]
09-02 09:53:50.279: E/AndroidRuntime(28022): java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
09-02 09:53:50.279: E/AndroidRuntime(28022): 	at android.graphics.Color.parseColor(Color.java:209)
09-02 09:53:50.279: E/AndroidRuntime(28022): 	at com.uservoice.uservoicesdk.activity.ForumActivity$1.customizeLayout(ForumActivity.java:151)
09-02 09:53:50.279: E/AndroidRuntime(28022): 	at com.uservoice.uservoicesdk.activity.ForumActivity$1.customizeLayout(ForumActivity.java:52)
09-02 09:53:50.279: E/AndroidRuntime(28022): 	at com.uservoice.uservoicesdk.ui.ModelAdapter.getView(ModelAdapter.java:41)
09-02 09:53:50.279: E/AndroidRuntime(28022): 	at com.uservoice.uservoicesdk.activity.ForumActivity$1.getView(ForumActivity.java:129)
09-02 09:53:50.279: E/AndroidRuntime(28022): 	at android.widget.AbsListView.obtainView(AbsListView.java:2346)

**Comment by gramarao** [comment]
We are using launchForum call from our app and when i try to post an idea/scroll existing items - VM crashes and above exception is seen in Android device monitor
