### ISSUE TITLE
Api::V1::BaseController::UnauthorizedException

### ISSUE THREAD

**Issue by rdlight75** [uservoice/uservoice-android-sdk#201]
Hello,

I was pointed here from UserVoice support for an issue that we're having with the Android SDK.  When attempting the submit an idea we see the error: "There was an error connecting to UserVoice". Oddly we're only seeing this on Samsung S4 and S5 devices. We're using version 1.2.+ at the moment. I've copied the errors mentioning UserVoice below. Please let me know if you'd like to see the rest of the log.

E/com.uservoice.uservoicesdk(24506): 401 -- {"errors":{"type":"unauthorized","message":"Api::V1::BaseController::UnauthorizedException"}}

E/com.uservoice.uservoicesdk(24506): Unable to resolve host "zlauncher.uservoice.com": No address associated with hostname -- null

W/System.err(24506): java.net.UnknownHostException: Unable to resolve host "by.uservoice.com": No address associated with hostname
W/System.err(24506): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
W/System.err(24506): 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
W/System.err(24506): 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
W/System.err(24506): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:172)
W/System.err(24506): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:167)
W/System.err(24506): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
W/System.err(24506): 	at org.apache.http.impl.client.DefaultRequestDirector.executeSB(DefaultRequestDirector.java:831)
W/System.err(24506): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:697)
W/System.err(24506): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
W/System.err(24506): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:491)
W/System.err(24506): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:469)
W/System.err(24506): 	at android.net.http.AndroidHttpClient.execute(AndroidHttpClient.java:302)
W/System.err(24506): 	at o.ᴝ.ˊ(:80)
W/System.err(24506): 	at o.ᴝ.doInBackground(:25)
W/System.err(24506): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err(24506): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(24506): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(24506): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(24506): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(24506): 	at java.lang.Thread.run(Thread.java:818)

Thanks for the help.

**Comment by banane** [comment]
I can try replicating on a Samsung- question: Are you able to access the url "zlauncher.uservoice.com" using a browser on the device?
