### ISSUE TITLE
Nullpointer in PortalAdapter

### ISSUE THREAD

**Issue by TepesLucian** [uservoice/uservoice-android-sdk#214]
Crash reported in crashlytics:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
       at com.uservoice.uservoicesdk.ui.PortalAdapter.getView(PortalAdapter.java:242)
       at android.widget.AbsListView.obtainView(AbsListView.java:2840)
       at android.widget.ListView.makeAndAddView(ListView.java:1903)
       at android.widget.ListView.fillDown(ListView.java:713)
       at android.widget.ListView.fillSpecific(ListView.java:1376)
       at android.widget.ListView.layoutChildren(ListView.java:1685)
       at android.widget.AbsListView.onLayout(AbsListView.java:2644)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2457)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2160)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7017)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6897)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by jdulaney** [comment]
Still an issue. Just received this same error via Crashlytics this morning.

UserVoice version: 1.2.5

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(int)' on a null object reference
       at com.uservoice.uservoicesdk.ui.PortalAdapter.getView(PortalAdapter.java:236)
       at android.widget.AbsListView.obtainView(AbsListView.java:2372)
       at android.widget.ListView.makeAndAddView(ListView.java:1970)
       at android.widget.ListView.fillDown(ListView.java:704)
       at android.widget.ListView.fillSpecific(ListView.java:1412)
       at android.widget.ListView.layoutChildren(ListView.java:1708)
       at android.widget.AbsListView.onLayout(AbsListView.java:2171)
       at android.view.View.layout(View.java:18585)
       at android.view.ViewGroup.layout(ViewGroup.java:5978)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:18585)
       at android.view.ViewGroup.layout(ViewGroup.java:5978)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:18585)
       at android.view.ViewGroup.layout(ViewGroup.java:5978)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
       at android.view.View.layout(View.java:18585)
       at android.view.ViewGroup.layout(ViewGroup.java:5978)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:18585)
       at android.view.ViewGroup.layout(ViewGroup.java:5978)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1768)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1612)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1521)
       at android.view.View.layout(View.java:18585)
       at android.view.ViewGroup.layout(ViewGroup.java:5978)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
       at android.view.View.layout(View.java:18585)
       at android.view.ViewGroup.layout(ViewGroup.java:5978)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2383)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2105)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1294)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6516)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6408)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:232)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```
