### ISSUE TITLE
IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by bearprada** [uservoice/uservoice-android-sdk#221]
I got a crash from Google Test Lab, it's happen when robot clicks into the uservoice page. here is the crash log :

` FATAL EXCEPTION: main Process: com.cardinalblue.piccollage.google, PID: 13145
 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
 	at android.view.ViewGroup.addViewInner(ViewGroup.java:3936)
 	at android.view.ViewGroup.addView(ViewGroup.java:3786)
 	at android.view.ViewGroup.addView(ViewGroup.java:3727)
 	at android.view.ViewGroup.addView(ViewGroup.java:3700)
 	at android.support.v7.widget.Toolbar.addChildrenForExpandedActionView(SourceFile:1801)
 	at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.collapseItemActionView(SourceFile:2040)
 	at android.support.v7.view.menu.MenuBuilder.collapseItemActionView(SourceFile:1345)
 	at android.support.v7.view.menu.MenuItemImpl.collapseActionView(SourceFile:704)
 	at android.support.v7.widget.Toolbar.collapseActionView(SourceFile:562)
 	at android.support.v7.widget.Toolbar$3.onClick(SourceFile:1057)
 	at android.view.View.performClick(View.java:4780)
 	at android.view.View$PerformClick.run(View.java:19866)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:135)
 	at android.app.ActivityThread.main(ActivityThread.java:5254)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

and the detail about test device

Screen Size: 1080 × 1920
Screen Density (dpi) : 480
Model Name : Nexus 5 (hammerhead)
OpenGL ES Version : 3.0
Native Platform : armeabi-v7a
Android Version : Android 5.1
RAM : 2048 MB

**Comment by okam1** [comment]
This issue is the same as #213

**Comment by ckompella** [comment]
I have the same issue. Is there a resolution for this?
