### ISSUE TITLE
IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by ckompella** [uservoice/uservoice-android-sdk#248]
After User does a search and clicks the back arrow on the status bar, I am seeing a crash with below stack. 

Is this fixed ? apreciate a response.

E/AndroidRuntime( 6318): java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

E/AndroidRuntime( 6318): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:3586)

E/AndroidRuntime( 6318): 	at android.view.ViewGroup.addView(ViewGroup.java:3439)

E/AndroidRuntime( 6318): 	at android.view.ViewGroup.addView(ViewGroup.java:3384)

E/AndroidRuntime( 6318): 	at android.view.ViewGroup.addView(ViewGroup.java:3360)

E/AndroidRuntime( 6318): 	at android.support.v7.widget.Toolbar.addChildrenForExpandedActionView(Toolbar.java:2137)

E/AndroidRuntime( 6318): 	at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.collapseItemActionView(Toolbar.java:2395)

E/AndroidRuntime( 6318): 	at android.support.v7.view.menu.MenuBuilder.collapseItemActionView(MenuBuilder.java:1357)

E/AndroidRuntime( 6318): 	at android.support.v7.view.menu.MenuItemImpl.collapseActionView(MenuItemImpl.java:708)

E/AndroidRuntime( 6318): 	at android.support.v7.widget.Toolbar.collapseActionView(Toolbar.java:719)

E/AndroidRuntime( 6318): 	at android.support.v7.widget.Toolbar$3.onClick(Toolbar.java:1384)

E/AndroidRuntime( 6318): 	at android.view.View.performClick(View.java:4452)

E/AndroidRuntime( 6318): 	at android.view.View$PerformClick.run(View.java:18451)

E/AndroidRuntime( 6318): 	at android.os.Handler.handleCallback(Handler.java:733)

E/AndroidRuntime( 6318): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime( 6318): 	at android.os.Looper.loop(Looper.java:136)

E/AndroidRuntime( 6318): 	at android.app.ActivityThread.main(ActivityThread.java:5421)

E/AndroidRuntime( 6318): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 6318): 	at java.lang.reflect.Method.invoke(Method.java:515)

E/AndroidRuntime( 6318): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
E/AndroidRuntime( 6318): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)

E/AndroidRuntime( 6318): 	at dalvik.system.NativeStart.main(Native Method)

W/ActivityManager(  587):   Force finishing activity  

Here is my gradle: 

    compile('com.uservoice:uservoice-android-sdk:1.2.5') {
        exclude module: 'commons-logging'
        exclude module: 'httpcore'
        exclude module: 'httpclient'
    }

**Comment by hossein-pdftron** [comment]
Is there any update on this issue, we are having the same problem in our app as well.

**Comment by hmrocket** [comment]
The app crash when the user visit any subject of the forum, and press back arrow at the top.

**Comment by intensemorpheus** [comment]
That's weird. Does that mean that me, a 24 year old woman has an boyfriend that's blocking shit from me



On Apr 18, 2018 at 11:11 AM, <hmrocket<mailto:notifications@github.com>> wrote:


The app crash when the user visit any subject of the forum, and press back arrow at the top.

**Comment by sgong-pdftron** [comment]
Any update on this issue?
