### ISSUE TITLE
BabayagaTask is failing to update to server

### ISSUE THREAD

**Issue by nalint2s** [uservoice/uservoice-android-sdk#263]
Hi Guys,
From today morning, I have been seeing this error on BabayagaTask update to server. It says "Expected ':status' header not present". We had similar issue with our service and had to update okhttp client library.

02-27 15:24:44.789 16662-17505/com.t2s.mytakeaway W/System.err: java.net.ProtocolException: Expected ':status' header not present
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.internal.http.SpdyTransport.readNameValueBlock(SpdyTransport.java:197)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.internal.http.SpdyTransport.readResponseHeaders(SpdyTransport.java:104)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:95)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:902)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:760)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:274)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:81)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.uservoice.uservoicesdk.babayaga.BabayagaTask.doInBackground(BabayagaTask.java:81)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at com.uservoice.uservoicesdk.babayaga.BabayagaTask.doInBackground(BabayagaTask.java:21)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-27 15:24:44.790 16662-17505/com.t2s.mytakeaway W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by jamerlan** [comment]
Fixed in 1.2.7
Make sure to review your app dependencies. New version of uservoice SDK using: okhttp to 3.10.0
