### ISSUE TITLE
Could not find Fragment constructor

### ISSUE THREAD

**Issue by DDRBoxman** [uservoice/uservoice-android-sdk#266]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fortmobile.parkingmobility/com.uservoice.uservoicesdk.activity.PortalActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.uservoice.uservoicesdk.dialog.SuggestionDialogFragment: could not find Fragment constructor
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4568)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6247)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.uservoice.uservoicesdk.dialog.SuggestionDialogFragment: could not find Fragment constructor
       at android.support.v4.app.Fragment.instantiate(Fragment.java:364)
       at android.support.v4.app.FragmentContainer.instantiate(FragmentContainer.java:33)
       at android.support.v4.app.FragmentState.instantiate(FragmentState.java:77)
       at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3065)
       at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:149)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:306)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
       at com.uservoice.uservoicesdk.activity.BaseActivity.onCreate(BaseActivity.java:24)
       at com.uservoice.uservoicesdk.activity.PortalActivity.onCreate(PortalActivity.java:17)
       at android.app.Activity.performCreate(Activity.java:6754)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4568)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6247)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by java.lang.NoSuchMethodException: <init> []
       at java.lang.Class.getConstructor0(Class.java:2204)
       at java.lang.Class.getConstructor(Class.java:1683)
       at android.support.v4.app.Fragment.instantiate(Fragment.java:345)
       at android.support.v4.app.FragmentContainer.instantiate(FragmentContainer.java:33)
       at android.support.v4.app.FragmentState.instantiate(FragmentState.java:77)
       at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3065)
       at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:149)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:306)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
       at com.uservoice.uservoicesdk.activity.BaseActivity.onCreate(BaseActivity.java:24)
       at com.uservoice.uservoicesdk.activity.PortalActivity.onCreate(PortalActivity.java:17)
       at android.app.Activity.performCreate(Activity.java:6754)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4568)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6247)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by waterPrince** [comment]
have you solve the problem?

**Comment by Fshiner** [comment]
Have you solve the problem?
I met a similar crash: 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.microsoft.launcher/com.uservoice.uservoicesdk.activity.ForumActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.uservoice.uservoicesdk.c.h: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2830)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2909)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4798)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.uservoice.uservoicesdk.c.h: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:462)
	at androidx.fragment.app.d.a(FragmentContainer.java:50)
	at androidx.fragment.app.FragmentState.a(FragmentState.java:80)
	at androidx.fragment.app.g.a(FragmentManager.java:3109)
	at androidx.fragment.app.e.a(FragmentController.java:158)
        ...
	at android.app.Activity.performCreate(Activity.java:6984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2783)
	... 10 more
Caused by: java.lang.NoSuchMethodException: <init> []
	at java.lang.Class.getConstructor0(Class.java:2320)
	at java.lang.Class.getConstructor(Class.java:1725)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:443)
	... 23 more
