### ISSUE TITLE
Crash NullPointerException on JSONObject

### ISSUE THREAD

**Issue by mtrezza** [uservoice/uservoice-android-sdk#282]
### Issue
This crash is reported consistently across a number of Android versions. I am not able to reproduce this issue however.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.getJSONObject(java.lang.String)' on a null object reference
       at com.uservoice.uservoicesdk.rest.RestResult.getType(RestResult.java:49)
       at com.uservoice.uservoicesdk.flow.InitManager$2$1.onError(InitManager.java:68)
       at com.uservoice.uservoicesdk.rest.RestTaskCallback.onComplete(RestTaskCallback.java:17)
       at com.uservoice.uservoicesdk.rest.RestTaskCallback.onError(RestTaskCallback.java:17)
       at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:101)
       at com.uservoice.uservoicesdk.rest.RestTask.onPostExecute(RestTask.java:26)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

### Environment
```
implementation('com.uservoice:uservoice-android-sdk:1.2.10') {
        exclude module: 'commons-logging'
        exclude module: 'httpcore'
        exclude module: 'httpclient'
    }
```

**Comment by mtrezza** [comment]
Possibly related to #171

**Comment by mtrezza** [comment]
@austintaylor can you please advice?

**Comment by mtrezza** [comment]
@amoore614 Can you please advice? We get quite a number of crashes for this issue.
