### ISSUE TITLE
NPE Resuming Application

### ISSUE THREAD

**Issue by PaitoAnderson** [uservoice/uservoice-android-sdk#89]
Got this report in Google Play Crashes & ANRs:

Android Version: 4.4
Android Device: Nexus 4 (mako)

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.skrumaz.app/com.uservoice.uservoicesdk.activity.ForumActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.uservoice.uservoicesdk.Config.getKey()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.uservoice.uservoicesdk.Config.getKey()' on a null object reference
at com.uservoice.uservoicesdk.model.ClientConfig.loadClientConfig(ClientConfig.java:28)
at com.uservoice.uservoicesdk.flow.InitManager.init(InitManager.java:28)
at com.uservoice.uservoicesdk.activity.ForumActivity.onCreate(ForumActivity.java:196)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
... 9 more
```

**Comment by austintaylor** [comment]
I believe this was fixed by 03f4ee0ba
